//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentingTaxiApi.Service.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminNotificationRead
    {
        public int notificationId { get; set; }
        public int adminId { get; set; }
        public Nullable<System.DateTime> read_time { get; set; }
    }
}
