//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentingTaxiApi.Service.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminSetting
    {
        public int adminsettingid { get; set; }
        public Nullable<long> searchdriverbuffer_sec { get; set; }
        public Nullable<int> driveravailabilityrange_min { get; set; }
        public Nullable<decimal> location_range_miles { get; set; }
        public string current_driver_ios_app_version { get; set; }
        public string current_driver_android_app_version { get; set; }
        public string current_user_ios_app_version { get; set; }
        public string current_user_android_app_version { get; set; }
    }
}
