//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentingTaxiApi.Service.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_trx
    {
        public int bookingId { get; set; }
        public Nullable<System.DateTime> booking_datetime { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> assigned_driverId { get; set; }
        public Nullable<int> booking_status { get; set; }
        public Nullable<int> request_Cartype { get; set; }
        public Nullable<decimal> from_lat { get; set; }
        public Nullable<decimal> from_lng { get; set; }
        public Nullable<decimal> to_Lat { get; set; }
        public Nullable<decimal> to_lng { get; set; }
        public Nullable<decimal> est_Distance { get; set; }
        public Nullable<decimal> est_Fares { get; set; }
        public Nullable<bool> manual_Assign_Flag { get; set; }
        public Nullable<System.DateTime> pickup_Datetime { get; set; }
        public Nullable<System.DateTime> journey_End_Datetime { get; set; }
        public Nullable<bool> usercall_flag { get; set; }
        public Nullable<bool> drivercall_flag { get; set; }
        public Nullable<bool> cancelleby_flag { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string from_locationname { get; set; }
        public string to_locationname { get; set; }
        public string remarks { get; set; }
        public Nullable<int> feedbackstatus { get; set; }
        public Nullable<int> manual_Assign_AdminId { get; set; }
        public Nullable<System.DateTime> manual_Assign_Datetime { get; set; }
        public Nullable<int> fdid_selected { get; set; }
    }
}
