//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentingTaxiApi.Service.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int driverId { get; set; }
        public string name { get; set; }
        public string ic { get; set; }
        public Nullable<int> gender { get; set; }
        public string car_Plate { get; set; }
        public string photo_url { get; set; }
        public string password { get; set; }
        public string password_salt { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> car_Type { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<decimal> priority_percentage { get; set; }
        public Nullable<decimal> current_lat { get; set; }
        public Nullable<decimal> current_lng { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string activation_code { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public Nullable<System.DateTime> code_sent_date { get; set; }
        public Nullable<bool> flg_ace_booking { get; set; }
        public Nullable<bool> islogin_flag { get; set; }
    }
}
