//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentingTaxiApi.Service.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int feedbackId { get; set; }
        public Nullable<int> userId { get; set; }
        public string remarks { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> bookingid { get; set; }
    }
}
