//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentingTaxiApi.Service.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gtaxidbEntities : DbContext
    {
        public gtaxidbEntities()
            : base("name=gtaxidbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<AdminNotification> AdminNotifications { get; set; }
        public DbSet<AdminNotificationRead> AdminNotificationReads { get; set; }
        public DbSet<AdminSetting> AdminSettings { get; set; }
        public DbSet<Booking_trx> Booking_trx { get; set; }
        public DbSet<City_queue> City_queue { get; set; }
        public DbSet<Driver> Drivers { get; set; }
        public DbSet<Driver_token> Driver_token { get; set; }
        public DbSet<DriverBooking> DriverBookings { get; set; }
        public DbSet<Errorlog> Errorlogs { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<Hotspot> Hotspots { get; set; }
        public DbSet<Hotspotpricing> Hotspotpricings { get; set; }
        public DbSet<Journey> Journeys { get; set; }
        public DbSet<Preferred_driver> Preferred_driver { get; set; }
        public DbSet<SMShistory> SMShistories { get; set; }
        public DbSet<Suggested_Location> Suggested_Location { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<User_token> User_token { get; set; }
    }
}
