//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentingTaxiApi.Service.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotspot
    {
        public int hotspotid { get; set; }
        public string hotspotname { get; set; }
        public Nullable<decimal> hotspot_lat { get; set; }
        public Nullable<decimal> hotspot_lng { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
