//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentingTaxiApi.Service.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey
    {
        public int journeyId { get; set; }
        public Nullable<int> bookingId { get; set; }
        public Nullable<System.DateTime> current_datetime { get; set; }
        public Nullable<decimal> current_lat { get; set; }
        public Nullable<decimal> current_lng { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
