//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentingTaxiApi.Service.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggested_Location
    {
        public int locationId { get; set; }
        public string locationName { get; set; }
        public Nullable<decimal> location_lat { get; set; }
        public Nullable<decimal> location_lng { get; set; }
    }
}
