//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentingTaxiApi.Service.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_token
    {
        public int unique_id { get; set; }
        public string token { get; set; }
        public string token_salt { get; set; }
        public Nullable<System.DateTime> token_expire { get; set; }
        public string os { get; set; }
        public string os_version { get; set; }
        public string model { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string deviceId { get; set; }
        public string app_version { get; set; }
        public Nullable<int> app_type { get; set; }
    }
}
