//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GentingTaxiApi.Service.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userId { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string name { get; set; }
        public int status { get; set; }
        public string password { get; set; }
        public string password_salt { get; set; }
        public Nullable<int> activation_status { get; set; }
        public string activation_code { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string host_address { get; set; }
        public Nullable<System.DateTime> code_sent_date { get; set; }
        public Nullable<bool> islogin_flag { get; set; }
    }
}
